version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://todouser:todopass@postgres:5432/todoapp"
      JWT_SECRET: "your-secret-key"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: